name = "ruixen"
type = "javascript"
compatibility_date = "2024-06-22"
account_id = "8295318475ba63f2e236f8b35d3682c1"
workers_dev = true

[build]
command = "bun run build"

[site]
bucket = "./dist"

[upload]
format = "modules"
main = "./dist/index.js"

[env.preview]
name = "ruixen-preview"
