name = "ruixen"
compatibility_date = "2024-06-22"
account_id = "8295318475ba63f2e236f8b35d3682c1"
workers_dev = true
main = "workers-site/index.js"

# Disable custom build to avoid Bun version mismatch
# [build]
# command = "bun run build"

[site]
bucket = "./public"

[env.preview]
name = "ruixen-preview"
