name = "ruixen"
compatibility_date = "2023-12-01"
account_id = "8295318475ba63f2e236f8b35d3682c1"
workers_dev = true
main = "./dist/worker.js"

[build]
command = "bun run build"

[env.preview]
name = "ruixen-preview"
