name = "ruixen"
type = "javascript"  # use "module" if using ESModules (import/export)
account_id = "8295318475ba63f2e236f8b35d3682c1"
workers_dev = true
main = "dist/index.js"

[build]
command = "bun run build"
upload = { dir = "./dist" }

[env.preview]
name = "ruixen-preview"
