name = "ruixen"
type = "javascript"  # or "module" if you're using ESModules

account_id = "your_actual_cloudflare_account_id"  # Get this from Cloudflare dashboard
workers_dev = true
main = "dist/index.js"

[build]
command = "bun run build"
upload = { dir = "./dist" }

[env.preview]
name = "ruixen-preview"
